# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

# Specify the Xcode project for the targets
project 'extApp.xcodeproj'

target 'extApp (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for extApp (iOS)


end

target 'extApp (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for extApp (macOS)

end

target 'extApp Extension (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for extApp Extension (iOS)

end

target 'extApp Extension (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for extApp Extension (macOS)

end
