# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafariExtension (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafariExtension (iOS)

end

target 'SafariExtension (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafariExtension (macOS)

end

target 'SafariExtension Extension (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafariExtension Extension (iOS)

end

target 'SafariExtension Extension (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafariExtension Extension (macOS)

end
