name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install dependencies
        run: composer install
        working-directory: ./WebAndApiExt
      - name: Build package
        run: php artisan package:discover && composer build
      - name: Publish package
        uses: peter-evans/create-release@v1
        with:
          tag_name: v${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.PAT }}
